"""changed the fav_color to bio

Revision ID: 1f03137e4a02
Revises: 6d93b1e63b47
Create Date: 2024-09-13 10:30:14.690736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f03137e4a02'
down_revision = '6d93b1e63b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=120), nullable=True))
        batch_op.drop_column('fav_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_color', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
