"""added profile pic field in the database

Revision ID: 371b014854d5
Revises: 79e06c903211
Create Date: 2024-09-15 18:10:13.991136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371b014854d5'
down_revision = '79e06c903211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
