"""Added User Model-correction

Revision ID: c7ff47b37e50
Revises: 885938bca59c
Create Date: 2024-09-06 10:50:58.868328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ff47b37e50'
down_revision = '885938bca59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=255), nullable=True))
        batch_op.drop_column('authors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###
